import { app, BrowserWindow } from 'electron';

import isDev from "electron-is-dev";
import App from "service";
// This allows TypeScript to pick up the magic constant that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;


let mainWindow: BrowserWindow = null;
new App(10000);

const createWindow = () => {
  mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
  });
  mainWindow.webContents.openDevTools();
  mainWindow.loadURL(isDev ? "http://localhost:8080" : MAIN_WINDOW_WEBPACK_ENTRY).then(r => console.log(r));
  mainWindow.on("closed", () => {
    mainWindow = null;
  });
};
app.on("ready", createWindow);
app.on("window-all-closed", () => {
  if (process.platform !== "darwin") {
    app.quit();
  }
});

app.on("activate", () => {
  if (mainWindow === null) {
    createWindow();
  }
});

